name: Python CI

on: [push]

jobs:
  code-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install black ruff
      - name: Run black checks
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "~= 23.0"
          checkName: "code-health"
      - name: Run ruff checks
        uses: chartboost/ruff-action@v1
        with:
          src: "."
          version: 0.0.265
          checkName: "code-health"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test_servers:
    permissions: write-all

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/436747687095/locations/global/workloadIdentityPools/github-action-usage/providers/github-provider"
          service_account: "flow-deployment@daring-runway-374503.iam.gserviceaccount.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel poetry keyrings.google-artifactregistry-auth
          poetry install

      - name: pytest with coverage
        run: |
          set -o pipefail
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=. | tee pytest-coverage.txt ; exit $?

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
